name: Update Data

on:
  push:
    branches: [ master ]
  watch:
    types: [ started ]
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout OwlAPI
      uses: actions/checkout@v2
      with:
        path: OwlAPI
        repository: OpenCourseAPI/OwlAPI

    - name: Setup OwlAPI
      working-directory: OwlAPI
      run: |
        sudo pip install pipenv
        pipenv install

    - name: Scrape data through OwlAPI
      working-directory: OwlAPI
      run: pipenv run python3 scrape_term.py

    - name: Copy data
      working-directory: OwlAPI
      run: |
        rsync -avr ./db/** ../main/data/

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v4
      with:
        cwd: "./main"
        author_name: OwlAPI Bot
        author_email: nonexistent@opencourse.dev
        message: "Update data"
        add: "./data"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
