name: Update Data

on:
  push:
    branches: [ master ]
  watch:
    types: [ started ]
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main

    - name: Checkout OwlAPI
      uses: actions/checkout@v2
      with:
        path: OwlAPI
        repository: OpenCourseAPI/OwlAPI

    - name: Setup OwlAPI
      working-directory: OwlAPI
      run: |
        sudo pip install pipenv
        pipenv install

    - name: Scrape data through OwlAPI
      working-directory: OwlAPI
      run: pipenv run python3 scrape_term.py

    - name: Copy data
      working-directory: OwlAPI
      run: |
        rsync -avr ./db/** ../main/data/

    - name: Push changes
      working-directory: main
      run: |
        git add --all
        git commit -m "Update data"
        git push
